#自动激活Lean Cloud
name: AutoWakeUpLeanCLoud/自动激活Lean Cloud

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: "0 0 * * *"   # 代表每天8:00执行一次
    # - cron: "*/18 0-15 * * *"  # 代表每天8点到晚上11:59执行
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    strategy:
      matrix:
        python-version: [3.8]  # 指定python的版本号
        
    steps:
    - name: Checkout/开始运行
      uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }} #安装python
      uses: actions/setup-python@v1
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install requests #安装requests
      run: |
        pip install requests

    - name: Waking/读取站点信息  #读取站点信息
      env: 
        $CONFIG_SITE: ${{ secrets.Site }} # 读取评论后台地址
      run: | 
        python run.py ${{ secrets.Site }}
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log

    - name: Commit/提交日志 #更新日志到GitHub仓库
      run: |
        git config --global user.name "${{secrets.GIT_NAME}}"
        git config --global user.email "${{secrets.GIT_EMAIL}}"
        git add .
        git commit -m "Successful Wake" -a

    - name: Push changes
      uses: ad-m/github-push-action@master  # 自动提交代码的 Actions
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}